service: 
  name: lambda-automation-test

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1
  role: arn:aws:iam::035257659693:role/serverless_agent_lambda_role

functions:
  helloFunction:
    handler: handler.sayHello
    description: Saying hello to the world
    events:
      - http:
          path: /
          method: get