# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: 
          name: Install serverless and deploy 
          command: |
            npm install
            # mkdir ~/.npm-global
            # npm config set prefix '~/.npm-global'
            # export PATH=~/.npm-global/bin:$PATH
            # source ~/.profile
            # npm config set unsafe-perm true
            # npm install -g serverless
            # serverless --version
            #ls
            git --version
            git commit -am 'Version auto updated by CircleCi'
            git push origin master
            #cat package.json
           # sed -i -e "s/.*Version.*/\"Version\": \"2"\"/" package.json
            # echo $AWS_ACCESS_KEY_ID
            # export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
            # export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
            # serverless deploy list

      # - run: 
      #     name: Deploy Lambda function
      #     command: serverless deploy list


      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      